# Generated by Django 5.0.3 on 2024-03-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_orders_orderproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barinventory',
            options={'managed': False, 'verbose_name_plural': 'Bar Inventories'},
        ),
        migrations.AlterModelOptions(
            name='bartables',
            options={'managed': False, 'verbose_name_plural': 'Bar Tables'},
        ),
        migrations.AlterModelOptions(
            name='branches',
            options={'managed': False, 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='employeeposition',
            options={'managed': False, 'verbose_name_plural': 'Employee Positions'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'managed': False, 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='employeeschedules',
            options={'managed': False, 'verbose_name_plural': 'Employee Schedules'},
        ),
        migrations.AlterModelOptions(
            name='feedbackreviews',
            options={'managed': False, 'verbose_name_plural': 'Feedback Reviews'},
        ),
        migrations.AlterModelOptions(
            name='guesses',
            options={'managed': False, 'verbose_name_plural': 'Guesses'},
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={'managed': False, 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'managed': False, 'verbose_name_plural': 'Memberships'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'managed': False, 'verbose_name_plural': 'Order Products'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'managed': False, 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='reservations',
            options={'managed': False, 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterModelOptions(
            name='securitylogs',
            options={'managed': False, 'verbose_name_plural': 'Security Logs'},
        ),
    ]
