# Generated by Django 5.0.3 on 2024-03-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_alter_barinventory_options_alter_bartables_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderproduct',
            table='orderproduct',
        ),
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
    ]
