# Generated by Django 5.0.3 on 2024-03-28 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('branch_ID', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=40)),
                ('employee_ID', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Position',
            fields=[
                ('position_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=30)),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('location_ID', models.AutoField(primary_key=True, serialize=False)),
                ('address_no', models.CharField(max_length=40)),
                ('street_name', models.CharField(max_length=30)),
                ('city_name', models.CharField(max_length=30)),
                ('province_name', models.CharField(blank=True, max_length=25, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=12, null=True)),
                ('country_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('contact_info', models.DecimalField(decimal_places=0, max_digits=12)),
                ('membership_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BarTables',
            fields=[
                ('table_ID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('table_status', models.BooleanField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.branches')),
            ],
            options={
                'db_table': 'BarTables',
            },
        ),
        migrations.CreateModel(
            name='Bar_Inventory',
            fields=[
                ('product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.branches')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Schedules',
            fields=[
                ('schedule_ID', models.AutoField(primary_key=True, serialize=False)),
                ('employee_ID', models.CharField(max_length=10)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.branches')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('contact_info', models.DecimalField(decimal_places=0, max_digits=12)),
                ('email', models.CharField(max_length=45)),
                ('salary', models.IntegerField()),
                ('hire_date', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.branches')),
                ('position_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee_position')),
            ],
        ),
        migrations.CreateModel(
            name='Guesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_ID', models.CharField(max_length=8)),
                ('guess_first_name', models.CharField(max_length=30)),
                ('guess_last_name', models.CharField(max_length=30)),
                ('guess_band', models.CharField(max_length=30)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.branches')),
            ],
        ),
        migrations.AddField(
            model_name='branches',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.locations'),
        ),
        migrations.CreateModel(
            name='Feedback_Reviews',
            fields=[
                ('review_ID', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('feedbacks', models.TextField()),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.membership')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservation_ID', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_time', models.TimeField()),
                ('number_of_guests', models.IntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.branches')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.membership')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bartables')),
            ],
        ),
        migrations.CreateModel(
            name='Security_Logs',
            fields=[
                ('log_ID', models.AutoField(primary_key=True, serialize=False)),
                ('employee_ID', models.CharField(max_length=10)),
                ('log_time', models.TimeField()),
                ('activity_log', models.BooleanField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.branches')),
            ],
        ),
        migrations.AddConstraint(
            model_name='guesses',
            constraint=models.UniqueConstraint(fields=('branch', 'table_ID'), name='unique_guess'),
        ),
    ]
